### ISSUE TITLE
Failed to get new exploration playlist

### ISSUE THREAD

**Issue by TobiasDax** [LumePart/Explo#7]
So... wwhen i run Explo (0.61) i only get
``` 
2024/10/24 20:01:21 using subsonic
2024/10/24 20:01:21 failed to get new exploration playlist, check if ListenBrainz has generated one
```

This seems strange to me, since there defently are two playlists on ListenBrainz ready for me and when i set `LISTENBRAINZ_DISCOVERY=api` it will download a playlist, but not one thats shown to me on the LB website.

here is my env file, but i don't think there is something missing here ;) i will try again next week but wanted to let you know of this possible problem.

````
# Music system you use (jellyfin, mpd or subsonic)
EXPLO_SYSTEM=subsonic
# Address of music system (required for subsonic, jellyfin)
SYSTEM_URL=http://192.168.1.123:4533
# User which has admin access to the music server (required for subsonic)
SYSTEM_USERNAME=***
# Password for the user (required for subsonic)
SYSTEM_PASSWORD=***
# API Key from music server (required for jellyfin)
API_KEY=
# Directory where to download tracks (required)
DOWNLOAD_DIR=/mnt/music/Music//Music/Explo/
# Directory where to make m3u playlist files (required for mpd)
PLAYLIST_DIR=/mnt/music/Music/Music/XX\ Playlists
# Username for ListenBrain recommendations (required)
LISTENBRAINZ_USER=***
# Youtube Data API key (required)
YOUTUBE_API_KEY=***

## Misc:

# Assign custom path to the ffmpeg binary
# FFMPEG_PATH=
# Define a custom filename sepatator for special characters
# FILENAME_SEPARATOR=
# true to keep pervious weeks discoveries, only set to false if the parent folder only contains discovered songs (deletes every file in folder)
# PERSIST=true
# 'playlist' to get tracks from Weekly Exploration playlist, anything else gets it from API (not the best recommendations). 'test' will download 1 song
LISTENBRAINZ_DISCOVERY=playlist
# Time to sleep (in minutes) between scanning and querying tracks from your system (If using Subsonic, Jellyfin)
# SLEEP=1
```

**Comment by LumePart** [comment]
This is an issue on ListenBrain's side. Lately their playlist generation seems to be getting stuck. If you view the creation times, they were most likely generated last week.
e.g 
![image](https://github.com/user-attachments/assets/af28dd20-15e9-4a19-a3cc-5f43f830b860)

Since no playlist for this week is found, Explo won't bother creating a playlist. [Heres a thread](https://community.metabrainz.org/t/weekly-jams-and-other-created-for-you-playlists-stuck/688969/10) for it on their forums, feel free to chime in, they're usually pretty responsive.
